# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]       
    set_property IOSTANDARD LVCMOS33 [get_ports clk]
    	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

# Create the clock with a 300 MHz frequency (period = 3.33 ns)
create_clock -add -name cpu_clk -period 3.33 [get_ports cpu_clk]
    	
set_property PACKAGE_PIN W19 [get_ports nRESET]     
    set_property IOSTANDARD LVCMOS33 [get_ports nRESET]

##Sch name = JA1
set_property PACKAGE_PIN G17 [get_ports {address[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[0]}]
set_property PACKAGE_PIN G18 [get_ports {address[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[1]}]
set_property PACKAGE_PIN G19 [get_ports {address[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[2]}]
set_property PACKAGE_PIN H1 [get_ports {address[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[3]}]
set_property PACKAGE_PIN H2 [get_ports {address[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[4]}]
set_property PACKAGE_PIN H19 [get_ports {address[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[5]}]
set_property PACKAGE_PIN J1 [get_ports {address[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[6]}]
set_property PACKAGE_PIN J2 [get_ports {address[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[7]}]
set_property PACKAGE_PIN J3 [get_ports {address[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[8]}]
set_property PACKAGE_PIN K18 [get_ports {address[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[9]}]
set_property PACKAGE_PIN K19 [get_ports {address[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[10]}]
set_property PACKAGE_PIN L1 [get_ports {address[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[11]}]
set_property PACKAGE_PIN L2 [get_ports {address[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[12]}]
set_property PACKAGE_PIN L3 [get_ports {address[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[13]}]
set_property PACKAGE_PIN N17 [get_ports {address[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[14]}]
set_property PACKAGE_PIN N18 [get_ports {address[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[15]}]
set_property PACKAGE_PIN N19 [get_ports {address[16]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[16]}]
set_property PACKAGE_PIN P1 [get_ports {address[17]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[17]}]
set_property PACKAGE_PIN P3 [get_ports {address[18]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[18]}]
set_property PACKAGE_PIN P17 [get_ports {address[19]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[19]}]
set_property PACKAGE_PIN P18 [get_ports {address[20]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[20]}]
set_property PACKAGE_PIN P19 [get_ports {address[21]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[21]}]
set_property PACKAGE_PIN T2 [get_ports {address[22]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[22]}]
set_property PACKAGE_PIN T3 [get_ports {address[23]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[23]}]
set_property PACKAGE_PIN T17 [get_ports {address[24]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[24]}]
set_property PACKAGE_PIN T18 [get_ports {address[25]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[25]}]
set_property PACKAGE_PIN U1 [get_ports {address[26]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[26]}]
set_property PACKAGE_PIN U2 [get_ports {address[27]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[27]}]
set_property PACKAGE_PIN U3 [get_ports {address[28]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[28]}]
set_property PACKAGE_PIN U4 [get_ports {address[29]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[29]}]
set_property PACKAGE_PIN U5 [get_ports {address[30]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[30]}]
set_property PACKAGE_PIN U7 [get_ports {address[31]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[31]}]
   
# Switches
set_property PACKAGE_PIN R2 [get_ports {read}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {read}]
set_property PACKAGE_PIN T1 [get_ports {write}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {write}]
	
##Pmod Header JB
##Sch name = JB2
set_property PACKAGE_PIN A16 [get_ports {CE0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CE0}]
##Sch name = JB8
set_property PACKAGE_PIN A17 [get_ports {CE1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CE1}]
##Sch name = JB3
set_property PACKAGE_PIN B15 [get_ports {OE0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {OE0}]
##Sch name = JB4
set_property PACKAGE_PIN B16 [get_ports {OE1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {OE1}]
##Sch name = JB9
set_property PACKAGE_PIN C15 [get_ports {WE0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {WE0}]
##Sch name = JB10 
set_property PACKAGE_PIN C16 [get_ports {WE1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {WE1}]

##Pmod Header JC
##Sch name = JC1
set_property PACKAGE_PIN K17 [get_ports {CS0}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CS0}]
##Sch name = JC7
set_property PACKAGE_PIN L17 [get_ports {CS1}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {CS1}]
##Sch name = JC2
set_property PACKAGE_PIN M18 [get_ports {WP}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {WP}]
